backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "campus"
    label: "Campus"
    folder: "src/pages/campuses"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "default"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "college"
    label: "College"
    folder: "src/pages/colleges"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "default"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Photos",name: "images",widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Campus", name: "campus",  widget: "select", options: ["main", "janiuay", "pototan", "himamaylan", "caf", "calinog"]}
      - {label: "Contact", name: "contact", widget: "markdown"}

  - name: "admin"
    label: "Admin Buildings"
    folder: "src/pages/admin"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "default"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Photos",name: "images",widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Campus", name: "campus",  widget: "select", options: ["main", "janiuay", "pototan", "himamaylan", "caf", "calinog"]}
      - {label: "Contact", name: "contact", widget: "markdown"}

  - name: "staff"
    label: "Staff"
    folder: "src/pages/staff"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "default"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Profile Image", name: "featuredimage", widget: image}      
      - {label: "Campus", name: "campus",  widget: "select", options: ["main", "janiuay", "pototan", "himamaylan", "caf", "calinog"]}
      - {label: "Office", name: "office",  widget: "list"}

  - name: "announcements"
    label: "Announcements"
    folder: "src/pages/announcements"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "default"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Profile Image", name: "featuredimage", widget: image}      
      - {label: "Campus", name: "campus",  widget: "select", options: ["main", "janiuay", "pototan", "himamaylan", "caf", "calinog"]}
      - {label: "Office", name: "office",  widget: "list"}
  
  - name: "messages"
    label: "Messages"
    folder: "src/pages/messages"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "default"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Position", name: "position", widget: "text"}
      - {label: "Profile Image", name: "featuredimage", widget: image}      
      - {label: "Office", name: "office",  widget: "list"}